apiVersion: v1
kind: Namespace
metadata:
  name: spring-cloud-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-cloud-gateway
  namespace: spring-cloud-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spring-cloud-gateway
rules:
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - services
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gateway-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spring-cloud-gateway
subjects:
- kind: ServiceAccount
  name: spring-cloud-gateway
  namespace: spring-cloud-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-gateway
  namespace: spring-cloud-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-cloud-gateway
  template:
    metadata:
      labels:
        app: spring-cloud-gateway
    spec:
      serviceAccountName: spring-cloud-gateway
      containers:
      - image: making/kubernetes-spring-cloud-gateway
        name: spring-cloud-gateway
        ports:
        - containerPort: 8080
        env: []
        resources:
          limits:
            memory: "386Mi"
          requests:
            memory: "386Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
---
kind: Service
apiVersion: v1
metadata:
  name: spring-cloud-gateway
  namespace: spring-cloud-gateway
  labels:
    app: spring-cloud-gateway
spec:
  type: NodePort
  selector:
    app: spring-cloud-gateway
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 32765
    name: http